# Generated by Django 5.1 on 2024-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0002_fundingtransaction_block_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingtransaction',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
