# Generated by Django 5.1 on 2024-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0003_fundingtransaction_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingtransaction',
            name='nonce',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
