# Generated by Django 5.1 on 2024-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0004_fundingtransaction_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingtransaction',
            name='nonce',
        ),
    ]
