version: '3.3'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: faucetango_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    container_name: faucetango_redis_celery_backend


  django:
    container_name: faucetango_django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - type: bind
        source: ./faucetapi/db.sqlite3
        target: /usr/src/app/db.sqlite3
    ports:
      - 8081:8080
    depends_on:
      - redis
      - rabbitmq

  celery:
    container_name: faucetango_celery_worker
    build:
      context: .
    command: celery --app=faucetapi worker -l INFO -Q celery1
    volumes:
      - type: bind
        source: ./faucetapi/db.sqlite3
        target: /usr/src/app/db.sqlite3
    depends_on:
      - rabbitmq
      - redis
      - django

