version: '3.3'

services:

#  redis-cache:
#    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./faucetapi
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./faucetapi:/usr/src/app/
    ports:
      - 8081:8080
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis-broker

