version: '3.3'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: faucetango_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    container_name: faucetango_redis_celery_backend


  django:
    container_name: faucetango_django
    build:
      context: .
    #env_file:
    #  - .env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8081:8080
    depends_on:
      - redis
      - rabbitmq

  celery:
    container_name: faucetango_celery_worker
    build:
      context: .
    #env_file:
    #  - .env
    command: celery --app=faucetapi worker -l INFO -Q celery:1,celery:2,celery:3
    depends_on:
      - rabbitmq
      - redis
      - django


