version: '3.3'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: faucetango_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    container_name: faucetango_redis_celery_backend


  django:
    container_name: faucetango_django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - type: bind
        source: ./faucetapi/db.sqlite3
        target: /usr/src/app/db.sqlite3
    ports:
      - 8081:8080
    depends_on:
      - redis
      - rabbitmq

  celery:
    container_name: faucetango_celery_worker
    build:
      context: .
    command: celery --app=faucetapi worker -l INFO -Q celery1
    volumes:
      - type: bind
        source: ./faucetapi/db.sqlite3
        target: /usr/src/app/db.sqlite3
    depends_on:
      - rabbitmq
      - redis
      - django

  prometheus:
    container_name: faucetango_prometheus
    image: prom/prometheus
    user: "1000:1000"
    restart: 'no'
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: "host"

  grafana:
    container_name: faucetango_grafana
    image: grafana/grafana
    user: "1000:1000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    network_mode: "host"